version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    user: "${UID}:${GID}"
    command: ["php-fpm"]
    volumes:
      - .:/var/www/html
    env_file:
      - .env.develop
    depends_on:
      - postgres
    networks:
      - callnet

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    user: "${UID}:${GID}"
    command: ["php", "artisan", "queue:work", "--tries=1", "--sleep=1"]
    volumes:
      - .:/var/www/html
    env_file:
      - .env.develop
    depends_on:
      - postgres
    networks:
      - callnet

  # одноразовый сервис: поставить зависимости + миграции
  init:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    user: "${UID}:${GID}"
    command: >
      bash -lc "
      composer install
      && php artisan key:generate --force
      && php artisan config:clear
      && php artisan cache:clear
      && php artisan migrate --force
      && php artisan storage:link
      "
    volumes:
      - .:/var/www/html
    env_file:
      - .env.develop
    depends_on:
      - postgres
    networks:
      - callnet
    restart: "no"

  nginx:
    image: nginx:1.25
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - callnet

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: call_center
      POSTGRES_PASSWORD: call_center
      POSTGRES_DB: call_center_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - callnet

  loki:
    image: grafana/loki:2.9.6
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - callnet

networks:
  callnet:
    driver: bridge

volumes:
  pgdata:
